swagger: "2.0"
info:
  version: "0.0.1"
  title: Cryptonames App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
# defines security
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: auth
paths:
  /names:
    x-swagger-router-controller: names
    get:
      description: Gets crypto names by tag
      security:
        - key: []
      operationId: getNames
      parameters:
        - name: tag
          in: query
          description: tag filter
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/NamesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  NamesListResponse:
    properties:
      names:
        type: array
        items: 
          type: string
      tag:
        type: string
    required:
      - names
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
